### ISSUE TITLE
Picture element not working (Nuxt.js typescript)

### ISSUE THREAD

**Issue by AndersNielsen85** [imgix/vue-imgix#163]
When trying to use the <ix-picture> I get an error "React is not defined".

Running environment on Nuxt.js typescript, with standard configuration copied from the readme.

Error in console:
![image](https://user-images.githubusercontent.com/48467762/87637130-11e1c880-c742-11ea-837e-cd48f058bc67.png)

Code (copied from readme and changed src):
`    <ix-picture>
      <ix-source src="femina/s3fs-public/media/article/fra-drivhus-til-orangeri-prim.jpg" media="(min-width:
  768px)" imgixParams="{ ar: '2:1' }"/>
      <ix-source src="femina/s3fs-public/media/article/fra-drivhus-til-orangeri-prim.jpg" media="(min-width: 320px)" imgixParams="{ ar: '1.5:1' }" />
      <ix-img src="femina/s3fs-public/media/article/fra-drivhus-til-orangeri-prim.jpg" imgixParams="{ w: 100, ar: '3:1' }" />
    </ix-picture>`

**Comment by frederickfogerty** [comment]
Hey there @AndersNielsen85, thanks for opening this issue 🙌 

This definitely seems to be a bug, and I can recreate this in a CodeSandbox. I'll work to get this fixed as soon as possible, and will post any updates here.

**Comment by frederickfogerty** [comment]
Hey @AndersNielsen85 - the PR above was merged and released in `2.8.1`. This should fix this issue for pictures and sources. Please let me know if you have any more issues. Thank you again for reaching out.
