### ISSUE TITLE
Responsive use of aspect ratio

### ISSUE THREAD

**Issue by funkeeflow** [imgix/vue-imgix#392]
Hello!

I'm right now trying to incorporate this into a nuxt + prismic.io project.
 This all looks great for now, but I cannot get my head around this.

How would you define responsive aspect ratios?
e.g. you have an image with an aspect ratio of 16:9 on desktop and a ratio of 1:1 on mobile.

Would that be possible with the api?

cheers
Florian

**Comment by sherwinski** [comment]
Hey @funkeeflow, it sounds like what you are looking for can be achieved with the `<ix-picture>` component. Feel free to check out [the example](https://github.com/imgix/vue-imgix#picture-support) in our documentation and let me know if it is helpful.

**Comment by sherwinski** [comment]
I'm going to close this issue for now, but please feel free to comment back if you have any more questions.
