### ISSUE TITLE
blurhash - v3.0.0-rc.1

### ISSUE THREAD

**Issue by productdevbook** [imgix/vue-imgix#434]
https://github.com/woltapp/blurhash

It would be great if you add this feature.

**Comment by frederickfogerty** [comment]
Hi @productdevbook, thanks for opening this issue. It's really helpful to us when community issues have more context around the specific problem that the user is having, any suggested solutions or implementations, and any other relevant context. Do you think you could provide some more information about why this is useful to you? For instance, blurhash requires server integration - is this something that already have set up? Also, imgix supports the blurhash feature manually with the `fm=blurhash` parameter if you feel like rolling your own.

**Comment by productdevbook** [comment]
yes, with used `imgix` but https://blurhash-vue.netlify.app/ pictures are not loading like here. It loads directly.

I think this library should take the blur from here and support this event

**Comment by luqven** [comment]
Hey, @productdevbook, I'm not sure I understand what you're trying to achieve.

The blog post linked in the example [outlines](https://ledermann.dev/blog/2020/08/01/progressive-image-loading-with-blurhash/) the backend setup needed for implementing blurhash. As @frederickfogerty suggested, you could generate your hashes using the [imgix API](https://docs.imgix.com/apis/rendering/format/fm#blurhash).

Do you think you could add a code snippet/sandbox how you're using/trying to use imgix with blurhash so I can better assist you?

**Comment by productdevbook** [comment]
```
<ix-img :src="[src](https://assets.imgix.net/hp/snowshoe.jpg?auto=compress&w=900&h=600&fit=crop?fm=blurhash)"
      loading="lazy" />
```
While loading, it doesn't load like blurhash at all, waits for the image and comes later.

**Comment by luqven** [comment]
Hey @productdevbook. 

The `src` above is malformed. You have two `?` in the query. If you swap the second `?` for a `&`, you'll get the image's blurhash returned, `https://assets.imgix.net/hp/snowshoe.jpg?auto=compress&w=900&h=600&fit=crop&fm=blurhash`.

I encourage you to read our [blog post ](https://blog.imgix.com/2021/01/26/blurhash)on how to use imgix with blurhash to learn more about using blurhashes. You can swap the example react blurhash library for a similar vue [library](https://www.npmjs.com/package/vue-blurhash).

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/155694807-9a21a11a-86ae-4e6a-85b2-246ac06b5e5d.png)

  <ix-img add src https://assets.imgix.net/hp/snowshoe.jpg?auto=compress&w=900&h=600&fit=crop&fm=blurhash dont see blur image :/

**Comment by luqven** [comment]
Hey @productdevbook 

The image URL with the blurhash parameter will return a hash, not an image. If you open the image URL in your browser you'll see the `eaKn#c-n%1M}RjK*SPNKWXjZF~WArrt6bbIvoINIxYbI0NbbWqR-xW` hash.

We can't set a hash as an image `src` URL. Rather, you need to give that hash to whatever component/library will make use of it to render the blurred image.

Again, I encourage you to read our [blog post](https://blog.imgix.com/2021/01/26/blurhash) on how to use blurhashes to learn more.

**Comment by luqven** [comment]
I'm going to go ahead and close this issue for now as there's hasn't been more movement on it.

**Comment by productdevbook** [comment]
If there is imgix blur feature, why doesn't this feature come installed in this library. I think it makes it difficult for us to write different codes for this feature. I think a special with Imgix should be here.
