### ISSUE TITLE
bug url change `?` auto `$3` - v3.0.0-rc.1

### ISSUE THREAD

**Issue by productdevbook** [imgix/vue-imgix#436]
https://images.unsplash.com/photo-1644757548216-99006a42419d?ixid=MnwzNjQxMnwwfDF8YWxsfHx8fHx8fHx8MTY0NDkxNDQyOA&ixlib=rb-1.2.1

iam send image url but change url `?` -> `%3`
https://images.unsplash.com/photo-1644757548216-99006a42419d%3Fixid=MnwzNjQxMnwwfDF8YWxsfHx8fHx8fHx8MTY0NDkxNDQyOA&ixlib=rb-1.2.1?ixlib=vue-3.0.0-rc.1

**Comment by productdevbook** [comment]
`19d%3Fixid=` `%3F` go to the library when the url comes, the question mark of the library writes a different text like 3%.

`19d?ixid=` true url

**Comment by luqven** [comment]
Hey @productdevbook , thanks for opening this issue.

It looks like the issue you're running into is that the `?` is getting double encoded. This happens if you pass an encoded URL. We expect all URLs to be provided un-encoded. So, in your case, if you'd passed `19d?ixid=` then we would have correctly encoded it to be `19d%3Fixid=`. But since you passed in `19d%3Fixid=` we will double-encode it, breaking the URL.

The README should be clearer on this point so apologies for any confusion.

We're discussing adding support for encoded URLs but do not have a timeline yet on if or when that might get added.

**Comment by luqven** [comment]
I'm going to go ahead and close this issue @productdevbook  (cc @frederickfogerty) since encoded URLs are not something we currently support. If you have any further questions/issues please feel free to re-open it.

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/154194636-f4de75fd-e447-42f1-95e2-911f0ea09182.png)
unsplash api urls. 

Unfortunately these come as urls and I have to use them. What solution can I get for this?

**Comment by luqven** [comment]
@productdevbook I'm going to go ahead and re-open this issue and mark it as `accepted`. As I said earlier, we can't give you an exact estimate of when it will be tackled as we're wrapping up some other integrations at the moment. Thanks again for reporting this.

**Comment by luqven** [comment]
For what it's worth, you can, for now, spit your URL path on the query params `?` and pass those params to the vue-imgix component. So for the `regular` image for example you could do:

```html
<script>
const buildParams(imageUrls:string) {
  const urlParams = imageUrl.split('?')[1]. // => '?crop=entropy&fit=max&...'
  const paramsObject = {}

  if(params.length){
    const paramsArray = urlParams.split('&')   // => ["crop=entropy", "fit=max", ... ]
    paramsArray.forEach((param, idx) => {      // => "crop=entropy"
       const [key, val] = param.split('=');    // => ["crop", "entropy"]
       paramsObject[key] = val;                // => {crop: "entropy"}
    }
  }
  return paramsObject; // => {crop: 'entropy'...}
}
</script>

// and later in your components

<vue-imgix 
  src={src}
  :imgixParams={`${buildParams(src)}`}
/>
```

Of course, this assumes that the URL query params map 1:1 to the imgix params API. You'd need to do some transformation in the event that they don't. 

It's not pretty but hopefully, this can help carry you over until we're able to tackle this issue.

**Comment by luqven** [comment]
I'm going to go ahead and close this issue for now as there hasn't been more movement on it. Please let us know in a comment if there's still interest in keeping this open.
